In [37]:
# scrape 
from bs4 import BeautifulSoup
from bs4 import BeautifulSoup as bs
from splinter import Browser
from splinter.exceptions import ElementDoesNotExist
import requests
import pandas as pd
import time

<h1># Windows Users</h1>

In [38]:
#Set the chromedriver path
executable_path = {"executable_path": "/users/evaeb/bin/chromedriver"}
browser = Browser("chrome", **executable_path, headless=False)

In [39]:
# Scrap Middle Eastern restaurants in New York
#url = 'https://www.zomato.com/houston/restaurants/middle-eastern'
n = 1
restaurant_name=[]
restaurant_address=[]
votes=[]
ratings=[]
costs=[]

for x in range(1, 30):
    url = f'https://www.zomato.com/houston/restaurants/mediterranean?page={n}'
    
    browser.visit(url)

    html = browser.html
    soup = bs(html, 'html.parser')
    restaurant_info = soup.find_all(class_='content')
    
    for restaurant in restaurant_info:
        
        try:
            rest_name= restaurant.find('a', class_='result-title').text     
            rest_address= restaurant.find(class_='search-result-address').text
            vote= restaurant.find('span').text
            rating= restaurant.find(class_='rating-popup').text
            cost= restaurant.find(class_="res-cost").text
            
                  
            restaurant_name.append(rest_name)
            restaurant_address.append(rest_address)
            votes.append(vote)
            ratings.append(rating)
            costs.append(cost)
            
        except:
            print("Not Available")
        
#         print(rest_name)
#         print(rest_address)
#         print(vote)
#         print(rating)
        n += 1

Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available
Not Available

In [40]:
restaurant_name

["Yia Yia Mary's\n                                    ",
 'Aladdin Mediterranean Cuisine\n                                    ',
 'Ephesus Mediterranean Grill\n                                    ',
 'Istanbul Grill & Deli\n                                    ',
 "Fadi's Meyerland Mediterranean Grill\n                                    ",
 "Dimassi's Mediterranean Buffet\n                                    ",
 'Mediterraneo Market & Cafe\n                                    ',
 'Alexander the Great\n                                    ',
 "Bibi's House of Kabob\n                                    ",
 'Lama Mediterranean Cafe\n                                    ',
 'Alwadi Mediterranean Sandwiches\n                                    ',
 'Empire Turkish Grill\n                                    ',
 "Wael's Mediterranean Cuisine\n                                    ",
 "Manny's Cafe\n                                    "]

In [41]:
restaurant_address

[' 4747 San Felipe 77056',
 ' 912 Westheimer Road, Houston 77006',
 ' 510 S Mason Road, Katy 77450',
 ' 5613 Morningside Drive, Houston 77005',
 ' 4738 Beechnut Street, Houston 77096',
 ' 1640 Lake Woodlands Drive, The Woodlands 77380',
 ' 18033 Upper Bay Road 77058',
 ' 3055 Sage Road 77056',
 ' 3121 Center Street, Deer Park 77536',
 ' 1500 Research Forest Drive, Suite 100, The Woodlands 77381',
 ' 15655 John F. Kennedy Boulevard, Suite J 77032',
 ' 12448 Memorial Drive, Houston 77024',
 ' 2449 Bay Area Boulevard, Houston 77058',
 ' 8475 Hwy 6 N, Houston 77095']

In [42]:
votes

['357 votes',
 '194 votes',
 '194 votes',
 '141 votes',
 '153 votes',
 '87 votes',
 '75 votes',
 '74 votes',
 '62 votes',
 '56 votes',
 '55 votes',
 '67 votes',
 '61 votes',
 '48 votes']

In [43]:
ratings

['\n                                        4.6\n                                    ',
 '\n                                        4.6\n                                    ',
 '\n                                        4.7\n                                    ',
 '\n                                        4.3\n                                    ',
 '\n                                        4.4\n                                    ',
 '\n                                        4.1\n                                    ',
 '\n                                        4.1\n                                    ',
 '\n                                        3.9\n                                    ',
 '\n                                        4.1\n                                    ',
 '\n                                        4.1\n                                    ',
 '\n                                        4.2\n                                    ',
 '\n                                        3.9\n                                    ',
 '\n                                        4.0\n                                    ',
 '\n                                        4.1\n                                    ']

In [44]:
df_restaurant_HOU_ME=pd.DataFrame({'Name': restaurant_name,
                                 'Address':restaurant_address,
                                 'Votes': votes,
                                 'Rating': ratings,'cost':costs})
df_restaurant_HOU_ME

,Name,Address,Votes,Rating,cost
0,Yia Yia Mary's\n ...,4747 San Felipe 77056,357 votes,\n 4.6\...,Cost for two:$85
1,Aladdin Mediterranean Cuisine\n ...,"912 Westheimer Road, Houston 77006",194 votes,\n 4.6\...,Cost for two:$30
2,Ephesus Mediterranean Grill\n ...,"510 S Mason Road, Katy 77450",194 votes,\n 4.7\...,Cost for two:$75
3,Istanbul Grill & Deli\n ...,"5613 Morningside Drive, Houston 77005",141 votes,\n 4.3\...,Cost for two:$40
4,Fadi's Meyerland Mediterranean Grill\n ...,"4738 Beechnut Street, Houston 77096",153 votes,\n 4.4\...,Cost for two:$35
5,Dimassi's Mediterranean Buffet\n ...,"1640 Lake Woodlands Drive, The Woodlands 77380",87 votes,\n 4.1\...,Cost for two:$75
6,Mediterraneo Market & Cafe\n ...,18033 Upper Bay Road 77058,75 votes,\n 4.1\...,Cost for two:$75
7,Alexander the Great\n ...,3055 Sage Road 77056,74 votes,\n 3.9\...,Cost for two:$60
8,Bibi's House of Kabob\n ...,"3121 Center Street, Deer Park 77536",62 votes,\n 4.1\...,Cost for two:$25
9,Lama Mediterranean Cafe\n ...,"1500 Research Forest Drive, Suite 100, The Wo...",56 votes,\n 4.1\...,Cost for two:$75
10,Alwadi Mediterranean Sandwiches\n ...,"15655 John F. Kennedy Boulevard, Suite J 77032",55 votes,\n 4.2\...,Cost for two:$25
11,Empire Turkish Grill\n ...,"12448 Memorial Drive, Houston 77024",67 votes,\n 3.9\...,Cost for two:$75
12,Wael's Mediterranean Cuisine\n ...,"2449 Bay Area Boulevard, Houston 77058",61 votes,\n 4.0\...,Cost for two:$25
13,Manny's Cafe\n ...,"8475 Hwy 6 N, Houston 77095",48 votes,\n 4.1\...,Cost for two:$25

In [45]:
df_restaurant_HOU_ME.drop_duplicates()

,Name,Address,Votes,Rating,cost
0,Yia Yia Mary's\n ...,4747 San Felipe 77056,357 votes,\n 4.6\...,Cost for two:$85
1,Aladdin Mediterranean Cuisine\n ...,"912 Westheimer Road, Houston 77006",194 votes,\n 4.6\...,Cost for two:$30
2,Ephesus Mediterranean Grill\n ...,"510 S Mason Road, Katy 77450",194 votes,\n 4.7\...,Cost for two:$75
3,Istanbul Grill & Deli\n ...,"5613 Morningside Drive, Houston 77005",141 votes,\n 4.3\...,Cost for two:$40
4,Fadi's Meyerland Mediterranean Grill\n ...,"4738 Beechnut Street, Houston 77096",153 votes,\n 4.4\...,Cost for two:$35
5,Dimassi's Mediterranean Buffet\n ...,"1640 Lake Woodlands Drive, The Woodlands 77380",87 votes,\n 4.1\...,Cost for two:$75
6,Mediterraneo Market & Cafe\n ...,18033 Upper Bay Road 77058,75 votes,\n 4.1\...,Cost for two:$75
7,Alexander the Great\n ...,3055 Sage Road 77056,74 votes,\n 3.9\...,Cost for two:$60
8,Bibi's House of Kabob\n ...,"3121 Center Street, Deer Park 77536",62 votes,\n 4.1\...,Cost for two:$25
9,Lama Mediterranean Cafe\n ...,"1500 Research Forest Drive, Suite 100, The Wo...",56 votes,\n 4.1\...,Cost for two:$75
10,Alwadi Mediterranean Sandwiches\n ...,"15655 John F. Kennedy Boulevard, Suite J 77032",55 votes,\n 4.2\...,Cost for two:$25
11,Empire Turkish Grill\n ...,"12448 Memorial Drive, Houston 77024",67 votes,\n 3.9\...,Cost for two:$75
12,Wael's Mediterranean Cuisine\n ...,"2449 Bay Area Boulevard, Houston 77058",61 votes,\n 4.0\...,Cost for two:$25
13,Manny's Cafe\n ...,"8475 Hwy 6 N, Houston 77095",48 votes,\n 4.1\...,Cost for two:$25

In [46]:
#### Save raw data to csv
df_restaurant_HOU_ME.to_csv('df_restaurant_HOU_ME_raw_EO.csv',index=False)